version: "3.8"
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: girishfury/devopsdb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
      - MYSQL_DATABASE=accounts

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

  vproapp:
    build:
      context: ./Docker-files/app
    image: girishfury/devopsapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproapp:/var/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: girishfury/devopsweb
    container_name: vproweb
    ports:
      - "80:80"
      
volumes:
  vproapp: {} 
  vprodata: {}