apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: DB
        image: girishfury/devopsdb
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: ebs-volume
        resources:
          requests:
            memory: "500m"
            cpu: "500m"
          limits:
            memory: "500m"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devops-secrets
              key: db_password
        - name: MYSQL_DATABASE
          value: "accounts"
      volumes:
      - name: ebs-volume
        persistentVolumeClaim:
          claimName: ebs-pvc
      nodeSelector:
        server: db