apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcache
  labels:
    app: memcache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcache
  template:
    metadata:
      labels:
        app: memcache
    spec:
      containers:
      - name: memcache
        image: memcached
        ports:
        - containerPort: 11211
      nodeSelector:
        server: db