apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq
  labels:
    app: mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
      - name: mq
        image: rabbitmq
        resources:
          requests:
            memory: "500m"
            cpu: "500m"
          limits:
            memory: "500m"
            cpu: "500m"
        ports:
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "test"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: devops-secrets
              key: mq_password