---
apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  selector:
    app: mq
  ports:
  - name: vpromq01
    protocol: TCP
    port: 15672
    targetPort: 15672

--- 
apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  selector:
    app: vprodb
  ports:
  - name: vprodb
    protocol: TCP
    port: 3306
    targetPort: 3306

--- 
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  selector:
    app: memcache
  ports:
  - name: vprocache01
    protocol: TCP
    port: 11211
    targetPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  name: frontapp
spec:
  selector:
    app: devopsapp
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer